name: C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: nlohmann-json
      run: sudo apt-get install nlohmann-json3-dev
    - name: argagg
      run: sudo apt-get install argagg-dev
    - name: xcb
      run: sudo apt-get install libx11-xcb-dev libxcb-xtest0-dev
    - name: make distclean
      run: make distclean
    - name: make check
      run: make check
