name: C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: apt-get update
      run: sudo apt-get update
    - name: nlohmann-json
      run: wget https://github.com/nlohmann/json/releases/latest/download/include.zip \
                unzip include.zip \
                sudo mv include/nlohmann /usr/include
    - name: argagg
      run: sudo apt-get install argagg-dev
    - name: xcb
      run: sudo apt-get install libx11-xcb-dev libxcb-xtest0-dev
    - name: configure
      run: ./configure
    - name: make distclean
      run: make distclean
    - name: make check
      run: make check
